/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_commissioning                  14
#define gattdb_attribute_1                    16
#define gattdb_attribute_2                    18
#define gattdb_attribute_3                    20
#define gattdb_test                           24


#endif // __GATT_DB_H
